// UI Reducer Types
export const TOGGLE_DRAWER = "TOGGLE_DRAWER";
export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const ADD_EXTENSION = "ADD_EXTENSION";
export const REMOVE_EXTENSION = "REMOVE_EXTENSION";

// Data Reducer Types
export const GET_CLASSROOMS = "GET_CLASSROOMS";
export const GET_CLASSROOM = "GET_CLASSROOM";
export const JOINED_CLASSROOM = "JOINED_CLASSROOM";
export const CREATED_ASSIGNMENT = "CREATED_ASSIGNMENT";
export const GET_SUBMISSIONS = "GET_SUBMISSIONS";

// User Reducer Types
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
